# CI/CD

image: archlinux
packages:
  - rustup
  - jq
sources:
  - https://git.sr.ht/~hadronized/kak-tree-sitter
tasks:
  - setup: |
      rustup set profile minimal
      rustup default stable
      rustup component add rustfmt clippy

  - check-default: |
      cd kak-tree-sitter
      cargo fmt --check
      cargo clippy -- -D warnings
  - check-all-features: |
      cd kak-tree-sitter
      cargo clippy --all-features --all-targets -- -D warnings

  # up-to-date build
  - build-default: |
      cd kak-tree-sitter
      cargo build
  - build-all-features: |
      cd kak-tree-sitter
      cargo build --all-features --all-targets
  - test-default: |
      cd kak-tree-sitter
      cargo test
  - test-all-features: |
      cd kak-tree-sitter
      cargo test --all-features --all-targets

  # minimal version build
  - build-minimal-default: |
      cd kak-tree-sitter
      cargo +nightly build -Z minimal-versions
  - build-minimal-all-features: |
      cd kak-tree-sitter
      cargo +nightly build -Z minimal-versions --all-features --all-targets
  - test-minimal-default: |
      cd kak-tree-sitter
      cargo +nightly test -Z minimal-versions
  - test-minimal-all-features: |
      cd kak-tree-sitter
      cargo +nightly test -Z minimal-versions --all-features --all-targets

  # MSRV build
  - build-msrv-default: |
      cd kak-tree-sitter
      RUST_VERSION=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[0].rust_version')
      rustup toolchain install $RUST_VERSION
      cargo +$RUST_VERSION build
  - build-msrv-all-features: |
      cd kak-tree-sitter
      RUST_VERSION=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[0].rust_version')
      rustup toolchain install $RUST_VERSION
      cargo +$RUST_VERSION build --all-features --all-targets
  - test-msrv-default: |
      cd kak-tree-sitter
      RUST_VERSION=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[0].rust_version')
      rustup toolchain install $RUST_VERSION
      cargo +$RUST_VERSION test
  - test-msrv-all-features: |
      cd kak-tree-sitter
      RUST_VERSION=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[0].rust_version')
      rustup toolchain install $RUST_VERSION
      cargo +$RUST_VERSION test --all-features --all-targets
